services:
  ceh-trainer:
    image: registry.ohrenpirat.de:5000/mwildt/ceh-trainer-api:latest
    build:
      context: .
      dockerfile: ceh-trainer.dockerfile
    environment:
      - API_KEY=geheim
    ports:
      - 8080:8080
